
services:

  # mongo database
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shashi
      - MONGO_INITDB_ROOT_PASSWORD=shashi10
      - MONGO_INITDB_DATABASE=admin

   # GUI for mongo
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=shashi
     - ME_CONFIG_MONGODB_ADMINPASSWORD=shashi10
     - ME_CONFIG_MONGODB_SERVER=mongodb

  # data-server
  data-server:
    build: ./data-server
    depends_on:
      - mongodb
    ports:
      - 8080:8080


  # meta-data server
  metadata-server:
    build: ./metadata-server
    depends_on:
      - mongodb
    ports:
      - 8082:8082

  # react client
  client:
    build: ./SN-Client
    depends_on:
      - data-server
      - metadata-server
    ports:
      - 3000:80

volumes:
  data:
    driver: local
